services:
  db:
    image: postgres:16-alpine
    container_name: prod-db
    restart: always
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: secretpassword123
      POSTGRES_DB: expense_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: lnp0806/expense-backend:latest
    container_name: prod-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: lnp0806/expense-frontend:latest
    container_name: prod-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
